from app import app
import os
from flask import request, jsonify
import resend

resend.api_key = os.getenv("RESEND_API_KEY")

@app.route("/email/send", methods = ["POST"])
def send_email():
    data = request.get_json()

    email = data.get("email")
    recipes = data.get("recipes")
    shopping_list = data.get("shopping_list")

    shopping_items_html = "".join([
        f"<li>{item['item']} — {item['quantity']}</li>"
        for item in shopping_list
    ])

    recipes_html = ""
    for recipe in recipes:
        ingredients_html = "".join([
            f"<li>{ing['item']} — {ing['quantity']}</li>"
            for ing in recipe['ingredients']
        ])
        steps_html = "".join([
            f"<li>{step}</li>"
            for step in recipe['steps']
        ])
        recipes_html += f"""
            <h3>{recipe['name']} ({recipe['meal']})</h3>
            <p><strong>Ingredients:</strong></p>
            <ul>{ingredients_html}</ul>
            <p><strong>Steps:</strong></p>
            <ol>{steps_html}</ol>
            <hr/>
        """

    html_content = f"""
        <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto;">
            <h1 style="color: #1e3d2f;">🛒 Your Grocera Shopping List</h1>

            <h2>Shopping List</h2>
            <ul>{shopping_items_html}</ul>

            <hr/>

            <h2>Recipes</h2>
            {recipes_html}

            <p style="color: #888; font-size: 0.85rem;">
                Generated by Grocera — Plan your meals, skip the stress.
            </p>
        </div>
    """

    try:
        resend.Emails.send({
            "from": "onboarding@resend.dev",
            "to": email,
            "subject": "Your Grocera Shopping List & Recipes 🛒",
            "html": html_content
        })
        return jsonify({ "success": True })
    except Exception as e:
        print("Email error:", e)
        return jsonify({ "success": False, "error": str(e)})